name: JavaScript workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu 19.10

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.13
        uses: actions/setup-node@v1
        with:
          node-version: "13.13"
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true