name: JavaScript workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.13
        uses: actions/setup-node@v1
        with:
          node-version: "13.13"
      - name: npm test
        run: npm test
        env:
          CI: true